/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarImages: typeof import('./components/car/CarImages.vue')['default']
    ContractTab: typeof import('./components/OrderDetail/ContractTab.vue')['default']
    CreateCity: typeof import('./components/CreateEntry/CreateCity.vue')['default']
    CustomerForm: typeof import('./components/Customer/CustomerForm.vue')['default']
    CustomerInfo: typeof import('./components/OrderDetail/CustomerInfo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MakeDialog: typeof import('./components/car/MakeDialog.vue')['default']
    ModelDialog: typeof import('./components/car/ModelDialog.vue')['default']
    OrderInfo: typeof import('./components/OrderDetail/OrderInfo.vue')['default']
    OrderItems: typeof import('./components/OrderDetail/OrderItems.vue')['default']
    OrderStatus: typeof import('./components/base/OrderStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionList: typeof import('./components/Home/SubscriptionList.vue')['default']
    TransportationTab: typeof import('./components/OrderDetail/TransportationTab.vue')['default']
    TrimDialog: typeof import('./components/car/TrimDialog.vue')['default']
  }
}
